services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8300:8300"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    networks:
      - existing-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./frontend:/app
    networks:
      - existing-network

networks:
  existing-network:
    external: true
    name: network